# Numpy

In [1]:
import numpy as np

### NumPy Array 
NumPy's arrays are way more compact than Python lists. A NumPy array is not required to be 1 dimensional.

In [3]:
np.__version__

'1.14.0'

In [7]:
l = [1, 2, 3, 4]
l * 3


[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [12]:
a = np.array(l)
#type(a)
a * 3
a.shape


(4,)

In [17]:
m = np.array([[7.1,8,9], [1,2,3]])
m

array([[7.1, 8. , 9. ],
       [1. , 2. , 3. ]])

`shape` method gives you the dimension (rows, columns) of an array. 
`dtype` method returns the data type

Note that how methods don't need parentheses unlike functions.

In [19]:
#m.shape
print(m.dtype)
m[1:1]

float64


array([], shape=(0, 3), dtype=float64)

To transpose an array use method `T`.

In [20]:
m.T

array([[7.1, 1. ],
       [8. , 2. ],
       [9. , 3. ]])

Here is some of most used NumPy functions:

In [36]:
#m.reshape(3,2)
print(np.diag(1))

ValueError: Input must be 1- or 2-d.

## *Exercise*
As you see np.ones() is producing float type ones. If you type a function with a question mark you can check the description. Can you write a 2 by 3 matrix of ones where the ones are integers?

In [37]:
np.ones?

In [42]:
np.ones((2,3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

NumPy functions are applicable on arrays

In [43]:
np.floor([3.14, 2.17, 1.41])

array([3., 2., 1.])

## *Exercise*
Given a matrix, can you return the sum of each row in an array?

In [44]:
np.sum?

*This section deduced from NN and Deep Learning from deeplearning.ai*

Implement a softmax function using numpy. 


- $ \text{for } x \in \mathbb{R}^{1\times n} \text{,     } softmax(x) = softmax(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}) = \begin{bmatrix}
     \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} $ 

- $\text{for a matrix } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ maps to the element in the $i^{th}$ row and $j^{th}$ column of $x$, thus we have: }$  $$softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} = \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    ...  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} $$

In [ ]:
def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (n, m).

    Argument:
    x -- A numpy matrix of shape (n,m)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (n,m)
    """
    
    # Apply exp() element-wise to x.
    x_exp = np.exp(x)
    print("x_exp shape is ",x_exp.shape)

    # Create a vector x_sum that sums each row of x_exp.
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    print("x_sum shape is ",x_sum.shape)
    
    # Compute softmax(x) by dividing x_exp by x_sum.
    s = x_exp/x_sum
    
    return s

In [ ]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

### Broadcasting
You divide a (2,5) matrix to a (2,1) vector. How is that possible?

[Broadcasting Documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html): The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 

## *Exercise*
Write a function that normalizes the element of a matrix based on sum of the elements in each column

In [52]:
def normalize(a):
    # write your code here
    colSum = np.sum(a,axis=0,keepdims = True)
    a = a/colSum
    return a

a = np.array([[1,2,3],
             [3,2,1]])
normalize(a)

array([[0.25, 0.5 , 0.75],
       [0.75, 0.5 , 0.25]])

In [49]:
1/6

0.16666666666666666